apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php-apache-mysql.fullname" . }}-db
  labels:
    {{- include "php-apache-mysql.labels" . | nindent 4 }}
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "php-apache-mysql.selectorLabels" . | nindent 6 }}
      app: db
  template:
    metadata:
      labels:
        {{- include "php-apache-mysql.selectorLabels" . | nindent 8 }}
        app: db 
    spec:
      serviceAccountName: {{ include "php-apache-mysql.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: .sweetpwd.
          - name: MYSQL_DATABASE
            value: my_db
          - name: MYSQL_USER
            value: db_user
          - name: MYSQL_PASSWORD
            value: .mypwd
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
